<a href="https://colab.research.google.com/github/mjnhcanhh/DA_CNPM/blob/main/Lab_1_Numpy_Panda.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:

!pip install numpy

import numpy as np

# 3.1. Tạo array 1-chiều
my_list = [1, 9, 15, 39]
my_numpy_array = np.array(my_list)
print('Numpy array 1D:', my_numpy_array)
print('Kích thước:', my_numpy_array.shape)

# 3.2. Array 2-chiều (Ma trận) [cite: 28]
c = np.array([(1, 2, 3), (4, 5, 6)])
print('\nArray 2D:\n', c)
print('Shape:', c.shape)

# 3.4. Tạo mảng với giá trị 0 hoặc 1 [cite: 68]
e = np.zeros((2, 2))
f = np.ones((3, 3))
print('\nZero matrix:\n', e)
print('One matrix:\n', f)

Numpy array 1D: [ 1  9 15 39]
Kích thước: (4,)

Array 2D:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)

Zero matrix:
 [[0. 0.]
 [0. 0.]]
One matrix:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [2]:
# 3.5.1. Reshape - Thay đổi kích thước [cite: 83]
g = np.array([[[1., 2., 3.], [4., 5., 6.]], [[7., 8., 9.], [10., 11., 12.]]])
h = g.reshape(3, 4) # Chuyển về 3 dòng 4 cột [cite: 104, 105]
print('Reshape (3, 4):\n', h)

# 3.5.2. Flatten - Chuyển về 1 chiều [cite: 146]
j = g.flatten()
print('\nFlatten array:', j)

# 3.6. Nối mảng hstack (ngang) và vstack (dọc) [cite: 170, 171, 172]
f_arr = np.array([1., 2., 3.])
g_arr = np.array([4., 5., 6.])
print('\nHorizontal Stack:', np.hstack((f_arr, g_arr)))
print('Vertical Stack:\n', np.vstack((f_arr, g_arr)))

Reshape (3, 4):
 [[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]

Flatten array: [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12.]

Horizontal Stack: [1. 2. 3. 4. 5. 6.]
Vertical Stack:
 [[1. 2. 3.]
 [4. 5. 6.]]


In [3]:
# 3.7.1. Sinh mảng số nguyên ngẫu nhiên [cite: 187]
rand_int = np.random.randint(100, size=(3, 4))
print('Random 2D Int:\n', rand_int)

# 3.7.3. Phân phối chuẩn Gaussian [cite: 245, 247]
# loc: trung tâm, scale: độ lệch chuẩn, size: số phần tử
gauss = np.random.normal(5, 0.5, 10)
print('\nGaussian distribution:', gauss)

# 3.9. Sinh dãy số [cite: 300]
arr_range = np.arange(1, 20, 2) # [cite: 306]
arr_linspace = np.linspace(1., 5., num=10) # Chia đều khoảng [cite: 312, 313]
print('\nArange:', arr_range)
print('Linspace:', arr_linspace)

Random 2D Int:
 [[76 31 76 61]
 [25  8  9 60]
 [ 9 11 12 64]]

Gaussian distribution: [5.76562762 4.83730718 5.34040833 5.67802409 4.81961796 4.78688486
 5.24875337 5.62590751 4.73749147 5.37740755]

Arange: [ 1  3  5  7  9 11 13 15 17 19]
Linspace: [1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


In [4]:
a = np.array([(1, 2, 3), (4, 5, 6)])
print('First row:', a[0]) # [cite: 327]
print('Second column:', a[:, 1]) # [cite: 331]
print('First two values of second row:', a[1, :2]) # [cite: 333]

First row: [1 2 3]
Second column: [2 5]
First two values of second row: [4 5]
